[package]
name = "device"
version = "0.1.0"
edition = "2021"

[dependencies]
controller = { path = "../controller" }
tokio = { version = "1.41.1", features = ["full"] }
runtime-tokio = { path = "../runtime-tokio" }
